dist: bionic

matrix:
  include:
    - name: PHP 7.1; Laravel 5.5
      env:
        - PHP_VERSION=7.1
        - LARAVEL_VERSION=5.5.*
        - SYMFONY_VERSION=^3.0
        - PHPUNIT_VERSION=^6.5
    - name: PHP 7.1; Laravel 5.6
      env:
        - PHP_VERSION=7.1
        - LARAVEL_VERSION=5.6.*
        - SYMFONY_VERSION=^4.0
        - PHPUNIT_VERSION=^7.5
    - name: PHP 7.1; Laravel 5.7
      env:
        - PHP_VERSION=7.1
        - LARAVEL_VERSION=5.7.*
        - SYMFONY_VERSION=^4.0
        - PHPUNIT_VERSION=^7.5
    - name: PHP 7.1; Laravel 5.8
      env:
        - PHP_VERSION=7.1
        - LARAVEL_VERSION=5.8.*
        - SYMFONY_VERSION=^4.0
        - PHPUNIT_VERSION=^7.5
    - name: PHP 7.2; Laravel 5.5
      env:
        - PHP_VERSION=7.2
        - LARAVEL_VERSION=5.5.*
        - SYMFONY_VERSION=^3.0
        - PHPUNIT_VERSION=^6.5
    - name: PHP 7.2; Laravel 5.6
      env:
        - PHP_VERSION=7.2
        - LARAVEL_VERSION=5.6.*
        - SYMFONY_VERSION=^4.0
        - PHPUNIT_VERSION=^7.5
    - name: PHP 7.2; Laravel 5.7
      env:
        - PHP_VERSION=7.2
        - LARAVEL_VERSION=5.7.*
        - SYMFONY_VERSION=^4.0
        - PHPUNIT_VERSION=^7.5
    - name: PHP 7.2; Laravel 5.8
      env:
        - PHP_VERSION=7.2
        - LARAVEL_VERSION=5.8.*
        - SYMFONY_VERSION=^4.0
        - PHPUNIT_VERSION=^8.0
    - name: PHP 7.2; Laravel 6
      env:
        - PHP_VERSION=7.2
        - LARAVEL_VERSION=^6.0
        - SYMFONY_VERSION=^4.0
        - PHPUNIT_VERSION=^8.0
    - name: PHP 7.3; Laravel 5.5
      env:
        - PHP_VERSION=7.3
        - LARAVEL_VERSION=5.5.*
        - SYMFONY_VERSION=^3.0
        - PHPUNIT_VERSION=^6.5
    - name: PHP 7.3; Laravel 5.6
      env:
        - PHP_VERSION=7.3
        - LARAVEL_VERSION=5.6.*
        - SYMFONY_VERSION=^4.0
        - PHPUNIT_VERSION=^7.5
    - name: PHP 7.3; Laravel 5.7
      env:
        - PHP_VERSION=7.3
        - LARAVEL_VERSION=5.7.*
        - SYMFONY_VERSION=^4.0
        - PHPUNIT_VERSION=^7.5
    - name: PHP 7.3; Laravel 5.8
      env:
        - PHP_VERSION=7.3
        - LARAVEL_VERSION=5.8.*
        - SYMFONY_VERSION=^4.0
        - PHPUNIT_VERSION=^8.0
    - name: PHP 7.3; Laravel 6
      env:
        - PHP_VERSION=7.3
        - LARAVEL_VERSION=^6.0
        - SYMFONY_VERSION=^4.0
        - PHPUNIT_VERSION=^8.0
    - name: PHP 7.4; Laravel 5.5
      env:
        - PHP_VERSION=7.4
        - LARAVEL_VERSION=5.5.*
        - SYMFONY_VERSION=^3.0
        - PHPUNIT_VERSION=^6.5
    - name: PHP 7.4; Laravel 5.6
      env:
        - PHP_VERSION=7.4
        - LARAVEL_VERSION=5.6.*
        - SYMFONY_VERSION=^4.0
        - PHPUNIT_VERSION=^7.5
    - name: PHP 7.4; Laravel 5.7
      env:
        - PHP_VERSION=7.4
        - LARAVEL_VERSION=5.7.*
        - SYMFONY_VERSION=^4.0
        - PHPUNIT_VERSION=^7.5
    - name: PHP 7.4; Laravel 5.8
      env:
        - PHP_VERSION=7.4
        - LARAVEL_VERSION=5.8.*
        - SYMFONY_VERSION=^4.0
        - PHPUNIT_VERSION=^8.0
    - name: PHP 7.4; Laravel 6
      env:
        - PHP_VERSION=7.4
        - LARAVEL_VERSION=^6.0
        - SYMFONY_VERSION=^4.0
        - PHPUNIT_VERSION=^8.0

sudo: false

install:
  - travis_retry composer install --no-interaction --prefer-source

script:
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" == "hhvm" ]; then vendor/bin/phpunit; fi;'
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then vendor/bin/phpunit --coverage-clover build/logs/clover.xml; fi;'

after_script:
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi;'
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml; fi;'git
        